# path
train_path: ./data/data
eval_path: ./data/data
model_path: ./model/textcnn/model
summary_path: ./model/textcnn/summary_path
predict_path: ./model/textcnn

# w2v
w2v_path: ./model/w2v/w2v.model

# logger setting
Server_Name: classification
LogLevel_Console: 10
LogLevel_File: 10
LogFile: log/classification.log
LogFormat: '%(asctime)s|%(levelname)s:%(message)s'